#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 28, 2020 05:20:24 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Buku Penghubung_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = main (root)
    Buku Penghubung_support.init(root, top)
    root.mainloop()

w = None
def create_main(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_main(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = main (w)
    Buku Penghubung_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_main():
    global w
    w.destroy()
    w = None

class main:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x540+255+100")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Buku Penghubung")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.welcome = tk.Label(top)
        self.welcome.place(relx=0.0, rely=0.315, height=60, width=600)
        self.welcome.configure(activebackground="#f9f9f9")
        self.welcome.configure(activeforeground="black")
        self.welcome.configure(background="#ffffff")
        self.welcome.configure(disabledforeground="#a3a3a3")
        self.welcome.configure(font="-family {Arcon Rounded-} -size 24 -weight bold")
        self.welcome.configure(foreground="#05bff5")
        self.welcome.configure(highlightbackground="#d9d9d9")
        self.welcome.configure(highlightcolor="black")
        self.welcome.configure(text='''Welcome to Buku Penghubung''')

        self.description = tk.Label(top)
        self.description.place(relx=0.0, rely=0.444, height=60, width=600)
        self.description.configure(activebackground="#f9f9f9")
        self.description.configure(activeforeground="black")
        self.description.configure(background="#05bff5")
        self.description.configure(disabledforeground="#a3a3a3")
        self.description.configure(font="-family {Arcon Rounded-} -size 12 -slant italic")
        self.description.configure(foreground="#ffffff")
        self.description.configure(highlightbackground="#d9d9d9")
        self.description.configure(highlightcolor="black")
        self.description.configure(text='''connect with your teachers, parents, 
and students more easily!''')

        self.register = tk.Button(top)
        self.register.place(relx=0.267, rely=0.611, height=30, width=120)
        self.register.configure(activebackground="#ececec")
        self.register.configure(activeforeground="#000000")
        self.register.configure(background="#ffffff")
        self.register.configure(disabledforeground="#a3a3a3")
        self.register.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.register.configure(foreground="#05bff5")
        self.register.configure(highlightbackground="#d9d9d9")
        self.register.configure(highlightcolor="black")
        self.register.configure(pady="0")
        self.register.configure(text='''REGISTER''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.483, rely=0.611, height=30, width=20)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''or''')

        self.login = tk.Button(top)
        self.login.place(relx=0.533, rely=0.611, height=30, width=120)
        self.login.configure(activebackground="#ececec")
        self.login.configure(activeforeground="#000000")
        self.login.configure(background="#ffffff")
        self.login.configure(disabledforeground="#a3a3a3")
        self.login.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.login.configure(foreground="#05bff5")
        self.login.configure(highlightbackground="#d9d9d9")
        self.login.configure(highlightcolor="black")
        self.login.configure(pady="0")
        self.login.configure(text='''LOGIN''')

if __name__ == '__main__':
    vp_start_gui()





