#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 28, 2020 08:32:25 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Forgot Password_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Forgot Password_support.set_Tk_var()
    top = register (root)
    Forgot Password_support.init(root, top)
    root.mainloop()

w = None
def create_register(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_register(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Forgot Password_support.set_Tk_var()
    top = register (w)
    Forgot Password_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_register():
    global w
    w.destroy()
    w = None

class register:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x540+255+100")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Register")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=-0.517, rely=-0.148, height=30, width=600)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ff8000")
        self.Label1.configure(borderwidth="0")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Arcon Rounded-} -size 10 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(justify='left')
        self.Label1.configure(text='''Buku Penghubung''')

        self.new_pass = tk.Label(top)
        self.new_pass.place(relx=0.2, rely=0.13, height=60, width=360)
        self.new_pass.configure(activebackground="#f9f9f9")
        self.new_pass.configure(activeforeground="black")
        self.new_pass.configure(background="#ffffff")
        self.new_pass.configure(borderwidth="0")
        self.new_pass.configure(disabledforeground="#ffffff")
        self.new_pass.configure(font="-family {Arcon Rounded-} -size 24 -weight bold")
        self.new_pass.configure(foreground="#05bff5")
        self.new_pass.configure(highlightbackground="#d9d9d9")
        self.new_pass.configure(highlightcolor="black")
        self.new_pass.configure(text='''Create New Password''')

        self.entry_name = tk.Entry(top)
        self.entry_name.place(relx=0.333, rely=0.389, height=25, relwidth=0.533)
        self.entry_name.configure(background="white")
        self.entry_name.configure(disabledbackground="white")
        self.entry_name.configure(disabledforeground="black")
        self.entry_name.configure(font="TkFixedFont")
        self.entry_name.configure(foreground="#000000")
        self.entry_name.configure(highlightbackground="#05bff5")
        self.entry_name.configure(highlightcolor="black")
        self.entry_name.configure(insertbackground="white")
        self.entry_name.configure(readonlybackground="white")
        self.entry_name.configure(selectbackground="#05bff5")
        self.entry_name.configure(selectforeground="white")
        self.entry_name.configure(textvariable=Forgot Password_support.name)

        self.entry_username = tk.Entry(top)
        self.entry_username.place(relx=0.333, rely=0.463, height=25
                , relwidth=0.533)
        self.entry_username.configure(background="white")
        self.entry_username.configure(disabledbackground="white")
        self.entry_username.configure(disabledforeground="black")
        self.entry_username.configure(font="TkFixedFont")
        self.entry_username.configure(foreground="#000000")
        self.entry_username.configure(highlightbackground="#05bff5")
        self.entry_username.configure(highlightcolor="black")
        self.entry_username.configure(insertbackground="white")
        self.entry_username.configure(readonlybackground="white")
        self.entry_username.configure(selectbackground="#05bff5")
        self.entry_username.configure(selectforeground="white")
        self.entry_username.configure(textvariable=Forgot Password_support.username)

        self.entry_phone_number = tk.Entry(top)
        self.entry_phone_number.place(relx=0.333, rely=0.537, height=25
                , relwidth=0.533)
        self.entry_phone_number.configure(background="white")
        self.entry_phone_number.configure(disabledbackground="white")
        self.entry_phone_number.configure(disabledforeground="black")
        self.entry_phone_number.configure(font="TkFixedFont")
        self.entry_phone_number.configure(foreground="#000000")
        self.entry_phone_number.configure(highlightbackground="#05bff5")
        self.entry_phone_number.configure(highlightcolor="black")
        self.entry_phone_number.configure(insertbackground="white")
        self.entry_phone_number.configure(readonlybackground="white")
        self.entry_phone_number.configure(selectbackground="#05bff5")
        self.entry_phone_number.configure(selectforeground="white")
        self.entry_phone_number.configure(textvariable=Forgot Password_support.phone_number)

        self.entry_address = tk.Entry(top)
        self.entry_address.place(relx=0.333, rely=0.611, height=25
                , relwidth=0.533)
        self.entry_address.configure(background="white")
        self.entry_address.configure(disabledbackground="white")
        self.entry_address.configure(disabledforeground="black")
        self.entry_address.configure(font="TkFixedFont")
        self.entry_address.configure(foreground="#000000")
        self.entry_address.configure(highlightbackground="#05bff5")
        self.entry_address.configure(highlightcolor="black")
        self.entry_address.configure(insertbackground="black")
        self.entry_address.configure(readonlybackground="white")
        self.entry_address.configure(selectbackground="#05bff5")
        self.entry_address.configure(selectforeground="white")
        self.entry_address.configure(textvariable=Forgot Password_support.address)

        self.entry_email = tk.Entry(top)
        self.entry_email.place(relx=0.333, rely=0.685, height=25, relwidth=0.533)

        self.entry_email.configure(background="white")
        self.entry_email.configure(disabledbackground="white")
        self.entry_email.configure(disabledforeground="black")
        self.entry_email.configure(font="TkFixedFont")
        self.entry_email.configure(foreground="#000000")
        self.entry_email.configure(highlightbackground="#05bff5")
        self.entry_email.configure(highlightcolor="black")
        self.entry_email.configure(insertbackground="black")
        self.entry_email.configure(readonlybackground="white")
        self.entry_email.configure(selectbackground="#05bff5")
        self.entry_email.configure(selectforeground="white")
        self.entry_email.configure(textvariable=Forgot Password_support.email)

        self.my_role = tk.Label(top)
        self.my_role.place(relx=0.1, rely=0.315, height=25, width=125)
        self.my_role.configure(activebackground="#f9f9f9")
        self.my_role.configure(activeforeground="black")
        self.my_role.configure(background="#ffffff")
        self.my_role.configure(disabledforeground="#a3a3a3")
        self.my_role.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.my_role.configure(foreground="#000000")
        self.my_role.configure(highlightbackground="#d9d9d9")
        self.my_role.configure(highlightcolor="black")
        self.my_role.configure(text='''MY ROLE                      :''')

        self.username = tk.Label(top)
        self.username.place(relx=0.1, rely=0.389, height=25, width=125)
        self.username.configure(activebackground="#f9f9f9")
        self.username.configure(activeforeground="black")
        self.username.configure(background="#ffffff")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(text='''USERNAME                  :''')

        self.phone_number = tk.Label(top)
        self.phone_number.place(relx=0.1, rely=0.537, height=25, width=125)
        self.phone_number.configure(activebackground="#f9f9f9")
        self.phone_number.configure(activeforeground="black")
        self.phone_number.configure(background="#ffffff")
        self.phone_number.configure(disabledforeground="#a3a3a3")
        self.phone_number.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.phone_number.configure(foreground="#000000")
        self.phone_number.configure(highlightbackground="#d9d9d9")
        self.phone_number.configure(highlightcolor="black")
        self.phone_number.configure(text='''VERIFICTION CODE    :''')

        self.address = tk.Label(top)
        self.address.place(relx=0.1, rely=0.611, height=25, width=125)
        self.address.configure(activebackground="#f9f9f9")
        self.address.configure(activeforeground="black")
        self.address.configure(background="#ffffff")
        self.address.configure(disabledforeground="#a3a3a3")
        self.address.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.address.configure(foreground="#000000")
        self.address.configure(highlightbackground="#d9d9d9")
        self.address.configure(highlightcolor="black")
        self.address.configure(text='''NEW PASSWORD       :''')

        self.email = tk.Label(top)
        self.email.place(relx=0.1, rely=0.463, height=25, width=125)
        self.email.configure(activebackground="#f9f9f9")
        self.email.configure(activeforeground="black")
        self.email.configure(background="#ffffff")
        self.email.configure(cursor="fleur")
        self.email.configure(disabledforeground="#a3a3a3")
        self.email.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.email.configure(foreground="#000000")
        self.email.configure(highlightbackground="#d9d9d9")
        self.email.configure(highlightcolor="black")
        self.email.configure(text='''EMAIL                            :''')

        self.password = tk.Label(top)
        self.password.place(relx=0.1, rely=0.685, height=25, width=125)
        self.password.configure(activebackground="#f9f9f9")
        self.password.configure(activeforeground="black")
        self.password.configure(background="#ffffff")
        self.password.configure(cursor="fleur")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(text='''RE-NEW PASSWORD :''')

        self.butt_submit = tk.Button(top)
        self.butt_submit.place(relx=0.4, rely=0.815, height=25, width=120)
        self.butt_submit.configure(activebackground="#ececec")
        self.butt_submit.configure(activeforeground="#000000")
        self.butt_submit.configure(background="#05bff5")
        self.butt_submit.configure(disabledforeground="#a3a3a3")
        self.butt_submit.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.butt_submit.configure(foreground="#ffffff")
        self.butt_submit.configure(highlightbackground="#d9d9d9")
        self.butt_submit.configure(highlightcolor="black")
        self.butt_submit.configure(pady="0")
        self.butt_submit.configure(text='''SUBMIT''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg='#ffffff',fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.title = tk.Label(top)
        self.title.place(relx=0.0, rely=0.0, height=30, width=600)
        self.title.configure(activebackground="#f9f9f9")
        self.title.configure(activeforeground="black")
        self.title.configure(background="#05bff5")
        self.title.configure(disabledforeground="#a3a3a3")
        self.title.configure(font="-family {Arcon Rounded-} -size 10 -weight bold")
        self.title.configure(foreground="#ffffff")
        self.title.configure(highlightbackground="#d9d9d9")
        self.title.configure(highlightcolor="black")
        self.title.configure(text='''Buku Penghubung''')

        self.student = tk.Radiobutton(top)
        self.student.place(relx=0.383, rely=0.315, relheight=0.046, relwidth=0.1)

        self.student.configure(activebackground="#ffffff")
        self.student.configure(activeforeground="#05bff5")
        self.student.configure(background="white")
        self.student.configure(cursor="fleur")
        self.student.configure(disabledforeground="#ffffff")
        self.student.configure(foreground="#000000")
        self.student.configure(highlightbackground="#ffffff")
        self.student.configure(highlightcolor="#05bff5")
        self.student.configure(justify='left')
        self.student.configure(text='''Student''')
        self.student.configure(variable=Forgot Password_support.selectedButton)

        self.teacher = tk.Radiobutton(top)
        self.teacher.place(relx=0.533, rely=0.315, relheight=0.046, relwidth=0.1)

        self.teacher.configure(activebackground="white")
        self.teacher.configure(activeforeground="#05bff5")
        self.teacher.configure(background="white")
        self.teacher.configure(disabledforeground="white")
        self.teacher.configure(foreground="#000000")
        self.teacher.configure(highlightbackground="white")
        self.teacher.configure(highlightcolor="#05bff5")
        self.teacher.configure(justify='left')
        self.teacher.configure(text='''Teacher''')
        self.teacher.configure(variable=Forgot Password_support.selectedButton)

        self.parent = tk.Radiobutton(top)
        self.parent.place(relx=0.683, rely=0.315, relheight=0.046
                , relwidth=0.097)
        self.parent.configure(activebackground="white")
        self.parent.configure(activeforeground="#05bff5")
        self.parent.configure(background="white")
        self.parent.configure(disabledforeground="white")
        self.parent.configure(foreground="#000000")
        self.parent.configure(highlightbackground="white")
        self.parent.configure(highlightcolor="#05bff5")
        self.parent.configure(justify='left')
        self.parent.configure(text='''Parent''')
        self.parent.configure(variable=Forgot Password_support.selectedButton)

if __name__ == '__main__':
    vp_start_gui()





