#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 28, 2020 02:32:48 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Login_support.set_Tk_var()
    top = register (root)
    Login_support.init(root, top)
    root.mainloop()

w = None
def create_register(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_register(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Login_support.set_Tk_var()
    top = register (w)
    Login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_register():
    global w
    w.destroy()
    w = None

class register:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x540+255+100")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Register")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.application = tk.Label(top)
        self.application.place(relx=0.0, rely=0.0, height=30, width=600)
        self.application.configure(activebackground="#f9f9f9")
        self.application.configure(activeforeground="black")
        self.application.configure(background="#05bff5")
        self.application.configure(borderwidth="0")
        self.application.configure(disabledforeground="#a3a3a3")
        self.application.configure(font="-family {Arcon Rounded-} -size 10 -weight bold")
        self.application.configure(foreground="#ffffff")
        self.application.configure(highlightbackground="#d9d9d9")
        self.application.configure(highlightcolor="black")
        self.application.configure(justify='left')
        self.application.configure(text='''Buku Penghubung''')

        self.login = tk.Label(top)
        self.login.place(relx=0.15, rely=0.204, height=60, width=420)
        self.login.configure(activebackground="#f9f9f9")
        self.login.configure(activeforeground="black")
        self.login.configure(background="#ffffff")
        self.login.configure(borderwidth="0")
        self.login.configure(disabledforeground="#ffffff")
        self.login.configure(font="-family {Arcon Rounded-} -size 24 -weight bold")
        self.login.configure(foreground="#05bff5")
        self.login.configure(highlightbackground="#d9d9d9")
        self.login.configure(highlightcolor="black")
        self.login.configure(text='''Login to Buku Penghubung''')

        self.student = tk.Checkbutton(top)
        self.student.place(relx=0.333, rely=0.426, relheight=0.046
                , relwidth=0.133)
        self.student.configure(activebackground="#ffffff")
        self.student.configure(activeforeground="#000000")
        self.student.configure(background="#ffffff")
        self.student.configure(disabledforeground="#05bff5")
        self.student.configure(foreground="#000000")
        self.student.configure(highlightbackground="#05bff5")
        self.student.configure(highlightcolor="#ffffff")
        self.student.configure(justify='left')
        self.student.configure(selectcolor="#05bff5")
        self.student.configure(text='''Student''')
        self.student.configure(variable=Login_support.che48)

        self.teacher = tk.Checkbutton(top)
        self.teacher.place(relx=0.483, rely=0.426, relheight=0.046
                , relwidth=0.133)
        self.teacher.configure(activebackground="#ffffff")
        self.teacher.configure(activeforeground="#000000")
        self.teacher.configure(background="#ffffff")
        self.teacher.configure(disabledforeground="#05bff5")
        self.teacher.configure(foreground="#000000")
        self.teacher.configure(highlightbackground="#05bff5")
        self.teacher.configure(highlightcolor="#ffffff")
        self.teacher.configure(justify='left')
        self.teacher.configure(selectcolor="#05bff5")
        self.teacher.configure(text='''Teacher''')
        self.teacher.configure(variable=Login_support.che49)

        self.parents = tk.Checkbutton(top)
        self.parents.place(relx=0.633, rely=0.426, relheight=0.046
                , relwidth=0.133)
        self.parents.configure(activebackground="#ffffff")
        self.parents.configure(activeforeground="#000000")
        self.parents.configure(background="#ffffff")
        self.parents.configure(disabledforeground="#05bff5")
        self.parents.configure(font="-family {Segoe UI} -size 9")
        self.parents.configure(foreground="#000000")
        self.parents.configure(highlightbackground="#05bff5")
        self.parents.configure(highlightcolor="#ffffff")
        self.parents.configure(justify='left')
        self.parents.configure(selectcolor="#05bff5")
        self.parents.configure(text='''Parents''')
        self.parents.configure(variable=Login_support.che50)

        self.entry_username = tk.Entry(top)
        self.entry_username.place(relx=0.333, rely=0.5, height=25
                , relwidth=0.533)
        self.entry_username.configure(background="white")
        self.entry_username.configure(disabledbackground="#ffffff")
        self.entry_username.configure(disabledforeground="#000000")
        self.entry_username.configure(font="TkFixedFont")
        self.entry_username.configure(foreground="#000000")
        self.entry_username.configure(highlightbackground="#05bff5")
        self.entry_username.configure(highlightcolor="black")
        self.entry_username.configure(insertbackground="#ffffff")
        self.entry_username.configure(readonlybackground="#ffffff")
        self.entry_username.configure(selectbackground="#05bff5")
        self.entry_username.configure(selectforeground="white")
        self.entry_username.configure(textvariable=Login_support.username)

        self.my_role = tk.Label(top)
        self.my_role.place(relx=0.1, rely=0.426, height=25, width=120)
        self.my_role.configure(activebackground="#f9f9f9")
        self.my_role.configure(activeforeground="black")
        self.my_role.configure(background="#ffffff")
        self.my_role.configure(disabledforeground="#a3a3a3")
        self.my_role.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.my_role.configure(foreground="#000000")
        self.my_role.configure(highlightbackground="#d9d9d9")
        self.my_role.configure(highlightcolor="black")
        self.my_role.configure(text='''MY ROLE                 :''')

        self.username = tk.Label(top)
        self.username.place(relx=0.1, rely=0.5, height=25, width=120)
        self.username.configure(activebackground="#f9f9f9")
        self.username.configure(activeforeground="black")
        self.username.configure(background="#ffffff")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(text='''USERNAME             :''')

        self.password = tk.Label(top)
        self.password.place(relx=0.1, rely=0.574, height=25, width=120)
        self.password.configure(activebackground="#f9f9f9")
        self.password.configure(activeforeground="black")
        self.password.configure(background="#ffffff")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(text='''PASSWORD            :''')

        self.butt_login = tk.Button(top)
        self.butt_login.place(relx=0.4, rely=0.741, height=25, width=120)
        self.butt_login.configure(activebackground="#ececec")
        self.butt_login.configure(activeforeground="#000000")
        self.butt_login.configure(background="#05bff5")
        self.butt_login.configure(disabledforeground="#a3a3a3")
        self.butt_login.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.butt_login.configure(foreground="#ffffff")
        self.butt_login.configure(highlightbackground="#d9d9d9")
        self.butt_login.configure(highlightcolor="black")
        self.butt_login.configure(pady="0")
        self.butt_login.configure(text='''LOGIN''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg='#ffffff',fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.forgot_pass = tk.Button(top)
        self.forgot_pass.place(relx=0.667, rely=0.63, height=15, width=120)
        self.forgot_pass.configure(activebackground="#ececec")
        self.forgot_pass.configure(activeforeground="#000000")
        self.forgot_pass.configure(background="#ffffff")
        self.forgot_pass.configure(disabledforeground="#a3a3a3")
        self.forgot_pass.configure(font="-family {Segoe UI} -size 8 -slant italic")
        self.forgot_pass.configure(foreground="#000000")
        self.forgot_pass.configure(highlightbackground="#d9d9d9")
        self.forgot_pass.configure(highlightcolor="black")
        self.forgot_pass.configure(pady="0")
        self.forgot_pass.configure(relief="flat")
        self.forgot_pass.configure(text='''forgot your password?''')

        self.entry_password = tk.Entry(top)
        self.entry_password.place(relx=0.333, rely=0.574, height=25
                , relwidth=0.533)
        self.entry_password.configure(background="white")
        self.entry_password.configure(disabledbackground="#ffffff")
        self.entry_password.configure(disabledforeground="#000000")
        self.entry_password.configure(font="TkFixedFont")
        self.entry_password.configure(foreground="#000000")
        self.entry_password.configure(highlightbackground="#05bff5")
        self.entry_password.configure(highlightcolor="black")
        self.entry_password.configure(insertbackground="#d9d9d9")
        self.entry_password.configure(readonlybackground="#ffffff")
        self.entry_password.configure(selectbackground="#05bff5")
        self.entry_password.configure(selectforeground="white")
        self.entry_password.configure(textvariable=Login_support.password)

if __name__ == '__main__':
    vp_start_gui()





