#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Dec 03, 2020 10:45:31 PM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x315+654+111
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 729
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Parent - Give Alert"
    vTcl:DefineAlias "$top" "parent_givealert" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground #ffffff -activeforeground #05bff5 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground #05bff5 -tearoff 0 
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add cascade \
        -menu "$top.m45.men46" -activebackground white \
        -activeforeground #05bff5 -background white -label Profile 
    set site_3_0 $top.m45
    menu $site_3_0.men46 \
        -activebackground white -activeforeground #05bff5 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground #05bff5 -tearoff 0 
    vTcl:DefineAlias "$site_3_0.men46" "navbar" vTcl:WidgetProc "" 1
    $site_3_0.men46 add command \
        -activebackground white -activeforeground #05bff5 -background white \
        -command {#} -foreground black -label {My Profile} 
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add cascade \
        -menu "$top.m45.men47" -label Children 
    set site_3_0 $top.m45
    menu $site_3_0.men47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0.men47 add command \
        -activebackground white -activeforeground #05bff5 -background white \
        -command {#} -foreground black -label {My Children} 
    $site_3_0.men47 add command \
        -activebackground white -activeforeground #05bff5 -background white \
        -command {#} -foreground black -label {My Child's Assignment} 
    $site_3_0.men47 add command \
        -activebackground white -activeforeground #05bff5 -background white \
        -command {#} -foreground black -label {Give Alert} 
    frame $top.fra49 \
        -borderwidth 2 -background #05bff5 -height 35 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 605 
    vTcl:DefineAlias "$top.fra49" "navbar" vTcl:WidgetProc "parent_givealert" 1
    set site_3_0 $top.fra49
    button $site_3_0.but51 \
        -activebackground white -activeforeground #000000 -background white \
        -disabledforeground black \
        -font {-family {Arcon Rounded-} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -relief flat -text Logout 
    vTcl:DefineAlias "$site_3_0.but51" "logout_butt" vTcl:WidgetProc "parent_givealert" 1
    label $site_3_0.lab55 \
        -activebackground #05bff5 -activeforeground white -background #05bff5 \
        -disabledforeground black \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground white -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Buku Penghubung} 
    vTcl:DefineAlias "$site_3_0.lab55" "app_name" vTcl:WidgetProc "parent_givealert" 1
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.9 -y 0 -width 60 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.2 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    labelframe $top.lab57 \
        -borderwidth 4 \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -relief flat -text Alert -background white \
        -height 285 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 580 
    vTcl:DefineAlias "$top.lab57" "main_alert" vTcl:WidgetProc "parent_givealert" 1
    set site_3_0 $top.lab57
    labelframe $site_3_0.lab58 \
        -font TkDefaultFont -foreground black -text Name \
        -background $vTcl(actual_gui_bg) -height 59 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_3_0.lab58" "set_name" vTcl:WidgetProc "parent_givealert" 1
    set site_4_0 $site_3_0.lab58
    entry $site_4_0.ent64 \
        -background white -disabledforeground #bfbfbf -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 330 
    vTcl:DefineAlias "$site_4_0.ent64" "entry_name" vTcl:WidgetProc "parent_givealert" 1
    place $site_4_0.ent64 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.364 -width 330 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but63 \
        -activebackground #05bff5 -activeforeground white -background white \
        -disabledforeground #bfbfbf \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text back 
    vTcl:DefineAlias "$site_3_0.but63" "back_butt" vTcl:WidgetProc "parent_givealert" 1
    labelframe $site_3_0.lab50 \
        -font TkDefaultFont -foreground black -text Message \
        -background $vTcl(actual_gui_bg) -height 119 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_3_0.lab50" "message" vTcl:WidgetProc "parent_givealert" 1
    set site_4_0 $site_3_0.lab50
    entry $site_4_0.ent64 \
        -background white -disabledforeground #bfbfbf -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 330 
    vTcl:DefineAlias "$site_4_0.ent64" "entry_message" vTcl:WidgetProc "parent_givealert" 1
    place $site_4_0.ent64 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.167 -width 330 \
        -relwidth 0 -height 90 -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but52 \
        -activebackground #05bff5 -activeforeground white -background white \
        -disabledforeground #bfbfbf \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text {send alert} 
    vTcl:DefineAlias "$site_3_0.but52" "send_butt" vTcl:WidgetProc "parent_givealert" 1
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.198 -y 0 -rely 0.091 -width 0 \
        -relwidth 0.603 -height 0 -relheight 0.218 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 0 -relx 0.362 -y 0 -rely 0.836 -width 60 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.198 -y 0 -rely 0.327 -width 0 \
        -relwidth 0.603 -height 0 -relheight 0.436 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.474 -y 0 -rely 0.836 -width 80 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra49 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 0.095 \
        -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.111 -width 0 -relwidth 0.967 \
        -height 0 -relheight 0.873 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

