#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Dec 04, 2020 04:24:43 AM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x420+654+111
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 729
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Parent - My Child's Assignment"
    vTcl:DefineAlias "$top" "parent_assignment" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground #ffffff -activeforeground #05bff5 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground #05bff5 -tearoff 0 
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add cascade \
        -menu "$top.m45.men46" -activebackground white \
        -activeforeground #05bff5 -background white -label Profile 
    set site_3_0 $top.m45
    menu $site_3_0.men46 \
        -activebackground white -activeforeground #05bff5 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground #05bff5 -tearoff 0 
    vTcl:DefineAlias "$site_3_0.men46" "navbar" vTcl:WidgetProc "" 1
    $site_3_0.men46 add command \
        -activebackground white -activeforeground #05bff5 -background white \
        -command {#} -foreground black -label {My Profile} 
    $top.m45 add separator \
        
    $top.m45 add separator \
        
    $top.m45 add cascade \
        -menu "$top.m45.men47" -label Children 
    set site_3_0 $top.m45
    menu $site_3_0.men47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0.men47 add command \
        -activebackground white -activeforeground #05bff5 -background white \
        -command {#} -foreground black -label {My Children} 
    $site_3_0.men47 add command \
        -activebackground white -activeforeground #05bff5 -background white \
        -command {#} -foreground black -label {My Child's Assignment} 
    $site_3_0.men47 add command \
        -activebackground white -activeforeground #05bff5 -background white \
        -command {#} -foreground black -label {Give Alert} 
    frame $top.fra49 \
        -borderwidth 2 -background #05bff5 -height 30 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 605 
    vTcl:DefineAlias "$top.fra49" "navbar" vTcl:WidgetProc "parent_assignment" 1
    set site_3_0 $top.fra49
    button $site_3_0.but51 \
        -activebackground white -activeforeground #000000 -background white \
        -disabledforeground black \
        -font {-family {Arcon Rounded-} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -relief flat -text Logout 
    vTcl:DefineAlias "$site_3_0.but51" "logout_butt" vTcl:WidgetProc "parent_assignment" 1
    label $site_3_0.lab55 \
        -activebackground #05bff5 -activeforeground white -background #05bff5 \
        -disabledforeground black \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground white -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Buku Penghubung} 
    vTcl:DefineAlias "$site_3_0.lab55" "app_name" vTcl:WidgetProc "parent_assignment" 1
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.9 -y 0 -width 60 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.2 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    labelframe $top.lab56 \
        \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -relief flat -text {My Child's Assignment} \
        -background $vTcl(actual_gui_bg) -height 395 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 580 
    vTcl:DefineAlias "$top.lab56" "main_assignment" vTcl:WidgetProc "parent_assignment" 1
    set site_3_0 $top.lab56
    labelframe $site_3_0.lab59 \
        -font TkDefaultFont -foreground black -text Name \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 150 
    vTcl:DefineAlias "$site_3_0.lab59" "child_name" vTcl:WidgetProc "parent_assignment" 1
    set site_4_0 $site_3_0.lab59
    entry $site_4_0.ent68 \
        -background white -disabledforeground #bfbfbf -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$site_4_0.ent68" "entry_name" vTcl:WidgetProc "parent_assignment" 1
    place $site_4_0.ent68 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.333 -width 320 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab64 \
        -font TkDefaultFont -foreground black -text {Assignment } \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 150 
    vTcl:DefineAlias "$site_3_0.lab64" "child_name_1" vTcl:WidgetProc "parent_assignment" 1
    set site_4_0 $site_3_0.lab64
    ttk::combobox $site_4_0.tCo63 \
        -values {{assignment name 1} {assignment name 2} {assignment name 3}} \
        -font TkTextFont -textvariable combobox -foreground black \
        -background white -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo63" "box_name_1" vTcl:WidgetProc "parent_assignment" 1
    place $site_4_0.tCo63 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.333 -width 0 \
        -relwidth 0.941 -height 0 -relheight 0.5 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab67 \
        -font TkDefaultFont -foreground black -text Detail \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 150 
    vTcl:DefineAlias "$site_3_0.lab67" "assignment_detail" vTcl:WidgetProc "parent_assignment" 1
    set site_4_0 $site_3_0.lab67
    labelframe $site_4_0.lab69 \
        -font TkDefaultFont -foreground black -text Desccription \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 320 
    vTcl:DefineAlias "$site_4_0.lab69" "description" vTcl:WidgetProc "parent_assignment" 1
    set site_5_0 $site_4_0.lab69
    text $site_5_0.tex46 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 -wrap word 
    $site_5_0.tex46 configure -font "TkTextFont"
    $site_5_0.tex46 insert end text
    vTcl:DefineAlias "$site_5_0.tex46" "get_assign_desc" vTcl:WidgetProc "parent_assignment" 1
    place $site_5_0.tex46 \
        -in $site_5_0 -x 0 -relx 0.031 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.938 -height 0 -relheight 0.684 -anchor nw \
        -bordermode ignore 
    labelframe $site_4_0.lab70 \
        -font TkDefaultFont -foreground black -text Deadline \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 320 
    vTcl:DefineAlias "$site_4_0.lab70" "dealine" vTcl:WidgetProc "parent_assignment" 1
    set site_5_0 $site_4_0.lab70
    text $site_5_0.tex47 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 -wrap word 
    $site_5_0.tex47 configure -font "TkTextFont"
    $site_5_0.tex47 insert end text
    vTcl:DefineAlias "$site_5_0.tex47" "get_deadline" vTcl:WidgetProc "parent_assignment" 1
    place $site_5_0.tex47 \
        -in $site_5_0 -x 0 -relx 0.065 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.871 -height 0 -relheight 0.455 -anchor nw \
        -bordermode ignore 
    labelframe $site_4_0.lab45 \
        -font TkDefaultFont -foreground black -text Status \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 320 
    vTcl:DefineAlias "$site_4_0.lab45" "status" vTcl:WidgetProc "parent_assignment" 1
    set site_5_0 $site_4_0.lab45
    text $site_5_0.tex48 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 -wrap word 
    $site_5_0.tex48 configure -font "TkTextFont"
    $site_5_0.tex48 insert end text
    vTcl:DefineAlias "$site_5_0.tex48" "get_status" vTcl:WidgetProc "parent_assignment" 1
    place $site_5_0.tex48 \
        -in $site_5_0 -x 0 -relx 0.065 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.871 -height 0 -relheight 0.455 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab69 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.086 -width 0 \
        -relwidth 0.941 -height 0 -relheight 0.543 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab70 \
        -in $site_4_0 -x 0 -relx 0.029 -y 0 -rely 0.629 -width 0 \
        -relwidth 0.456 -height 0 -relheight 0.314 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 0 -relx 0.515 -y 0 -rely 0.629 -width 0 \
        -relwidth 0.456 -height 0 -relheight 0.314 -anchor nw \
        -bordermode ignore 
    button $site_3_0.but49 \
        -activebackground #05bff5 -activeforeground white \
        -background $vTcl(actual_gui_bg) -disabledforeground #bfbfbf \
        -font {-family {Arcon Rounded-} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text back 
    vTcl:DefineAlias "$site_3_0.but49" "back_butt" vTcl:WidgetProc "parent_assignment" 1
    button $site_3_0.but50 \
        -activebackground #05bff5 -activeforeground white \
        -background $vTcl(actual_gui_bg) -disabledforeground #bfbfbf \
        -font {-family {Arcon Rounded-} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text alert 
    vTcl:DefineAlias "$site_3_0.but50" "alert" vTcl:WidgetProc "parent_assignment" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.207 -y 0 -rely 0.079 -width 0 \
        -relwidth 0.586 -height 0 -relheight 0.15 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.207 -y 0 -rely 0.236 -width 0 \
        -relwidth 0.586 -height 0 -relheight 0.15 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.207 -y 0 -rely 0.393 -width 0 \
        -relwidth 0.586 -height 0 -relheight 0.458 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.388 -y 0 -rely 0.89 -width 60 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.509 -y 0 -rely 0.89 -width 60 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra49 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 0.068 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.083 -width 0 -relwidth 0.967 \
        -height 0 -relheight 0.91 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

