#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Dec 04, 2020 04:24:54 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Parent - My Child's Assignment_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Parent - My Child's Assignment_support.set_Tk_var()
    top = parent_assignment (root)
    Parent - My Child's Assignment_support.init(root, top)
    root.mainloop()

w = None
def create_parent_assignment(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_parent_assignment(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Parent - My Child's Assignment_support.set_Tk_var()
    top = parent_assignment (w)
    Parent - My Child's Assignment_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_parent_assignment():
    global w
    w.destroy()
    w = None

class parent_assignment:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x420+654+111")
        top.minsize(120, 1)
        top.maxsize(1370, 729)
        top.resizable(1,  1)
        top.title("Parent - My Child's Assignment")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#ffffff")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg='#05bff5')
        top.configure(menu = self.menubar)

        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.sub_menu = tk.Menu(top,
                activebackground="white",
                activeborderwidth=1,
                activeforeground="#05bff5",
                background="#ffffff",
                borderwidth=1,
                disabledforeground="#bfbfbf",
                foreground="#05bff5",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                label="Profile")
        self.sub_menu.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="My Profile")
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.sub_menu1 = tk.Menu(top,
                activebackground="#ececec",
                activeborderwidth=1,
                activeforeground="#000000",
                background="#ffffff",
                borderwidth=1,
                disabledforeground="#bfbfbf",
                foreground="#000000",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu1,
                label="Children")
        self.sub_menu1.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="My Children")
        self.sub_menu1.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="My Child's Assignment")
        self.sub_menu1.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="Give Alert")

        self.navbar = tk.Frame(top)
        self.navbar.place(relx=0.0, rely=0.0, relheight=0.069, relwidth=1.0)
        self.navbar.configure(relief='flat')
        self.navbar.configure(borderwidth="2")
        self.navbar.configure(background="#05bff5")
        self.navbar.configure(highlightbackground="#ffffff")
        self.navbar.configure(highlightcolor="black")

        self.logout_butt = tk.Button(self.navbar)
        self.logout_butt.place(relx=0.9, rely=0.0, height=30, width=60)
        self.logout_butt.configure(activebackground="white")
        self.logout_butt.configure(activeforeground="#000000")
        self.logout_butt.configure(background="white")
        self.logout_butt.configure(disabledforeground="black")
        self.logout_butt.configure(font="-family {Arcon Rounded-} -size 9")
        self.logout_butt.configure(foreground="#05bff5")
        self.logout_butt.configure(highlightbackground="#ffffff")
        self.logout_butt.configure(highlightcolor="black")
        self.logout_butt.configure(pady="0")
        self.logout_butt.configure(relief="flat")
        self.logout_butt.configure(text='''Logout''')

        self.app_name = tk.Label(self.navbar)
        self.app_name.place(relx=0.0, rely=0.0, height=29, width=120)
        self.app_name.configure(activebackground="#05bff5")
        self.app_name.configure(activeforeground="white")
        self.app_name.configure(background="#05bff5")
        self.app_name.configure(disabledforeground="black")
        self.app_name.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.app_name.configure(foreground="white")
        self.app_name.configure(highlightbackground="#ffffff")
        self.app_name.configure(highlightcolor="black")
        self.app_name.configure(text='''Buku Penghubung''')

        self.main_assignment = tk.LabelFrame(top)
        self.main_assignment.place(relx=0.017, rely=0.083, relheight=0.91
                , relwidth=0.967)
        self.main_assignment.configure(relief='flat')
        self.main_assignment.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.main_assignment.configure(foreground="black")
        self.main_assignment.configure(relief="flat")
        self.main_assignment.configure(text='''My Child's Assignment''')
        self.main_assignment.configure(background="#ffffff")
        self.main_assignment.configure(highlightbackground="#ffffff")
        self.main_assignment.configure(highlightcolor="black")

        self.child_name = tk.LabelFrame(self.main_assignment)
        self.child_name.place(relx=0.207, rely=0.079, relheight=0.149
                , relwidth=0.586, bordermode='ignore')
        self.child_name.configure(relief='groove')
        self.child_name.configure(foreground="black")
        self.child_name.configure(text='''Name''')
        self.child_name.configure(background="#ffffff")
        self.child_name.configure(highlightbackground="#ffffff")
        self.child_name.configure(highlightcolor="black")

        self.entry_name = tk.Entry(self.child_name)
        self.entry_name.place(relx=0.029, rely=0.333, height=30, relwidth=0.941
                , bordermode='ignore')
        self.entry_name.configure(background="white")
        self.entry_name.configure(disabledforeground="#bfbfbf")
        self.entry_name.configure(font="TkFixedFont")
        self.entry_name.configure(foreground="#000000")
        self.entry_name.configure(highlightbackground="#ffffff")
        self.entry_name.configure(highlightcolor="black")
        self.entry_name.configure(insertbackground="black")
        self.entry_name.configure(selectbackground="blue")
        self.entry_name.configure(selectforeground="white")

        self.child_name_1 = tk.LabelFrame(self.main_assignment)
        self.child_name_1.place(relx=0.207, rely=0.236, relheight=0.149
                , relwidth=0.586, bordermode='ignore')
        self.child_name_1.configure(relief='groove')
        self.child_name_1.configure(foreground="black")
        self.child_name_1.configure(text='''Assignment''')
        self.child_name_1.configure(background="#ffffff")
        self.child_name_1.configure(highlightbackground="#ffffff")
        self.child_name_1.configure(highlightcolor="black")

        self.box_name_1 = ttk.Combobox(self.child_name_1)
        self.box_name_1.place(relx=0.029, rely=0.333, relheight=0.491
                , relwidth=0.941, bordermode='ignore')
        self.value_list = ['assignment name 1','assignment name 2','assignment name 3',]
        self.box_name_1.configure(values=self.value_list)
        self.box_name_1.configure(textvariable=Parent - My Child's Assignment_support.combobox)
        self.box_name_1.configure(foreground="black")
        self.box_name_1.configure(background="white")
        self.box_name_1.configure(takefocus="")

        self.assignment_detail = tk.LabelFrame(self.main_assignment)
        self.assignment_detail.place(relx=0.207, rely=0.393, relheight=0.458
                , relwidth=0.586, bordermode='ignore')
        self.assignment_detail.configure(relief='groove')
        self.assignment_detail.configure(foreground="black")
        self.assignment_detail.configure(text='''Detail''')
        self.assignment_detail.configure(background="#ffffff")
        self.assignment_detail.configure(highlightbackground="#ffffff")
        self.assignment_detail.configure(highlightcolor="black")

        self.description = tk.LabelFrame(self.assignment_detail)
        self.description.place(relx=0.029, rely=0.086, relheight=0.543
                , relwidth=0.941, bordermode='ignore')
        self.description.configure(relief='groove')
        self.description.configure(foreground="black")
        self.description.configure(text='''Desccription''')
        self.description.configure(background="#ffffff")
        self.description.configure(highlightbackground="#ffffff")
        self.description.configure(highlightcolor="black")

        self.get_assign_desc = tk.Text(self.description)
        self.get_assign_desc.place(relx=0.031, rely=0.211, relheight=0.684
                , relwidth=0.938, bordermode='ignore')
        self.get_assign_desc.configure(background="white")
        self.get_assign_desc.configure(font="TkTextFont")
        self.get_assign_desc.configure(foreground="black")
        self.get_assign_desc.configure(highlightbackground="#ffffff")
        self.get_assign_desc.configure(highlightcolor="black")
        self.get_assign_desc.configure(insertbackground="black")
        self.get_assign_desc.configure(selectbackground="blue")
        self.get_assign_desc.configure(selectforeground="white")
        self.get_assign_desc.configure(wrap="word")

        self.dealine = tk.LabelFrame(self.assignment_detail)
        self.dealine.place(relx=0.029, rely=0.629, relheight=0.314
                , relwidth=0.456, bordermode='ignore')
        self.dealine.configure(relief='groove')
        self.dealine.configure(foreground="black")
        self.dealine.configure(text='''Deadline''')
        self.dealine.configure(background="#ffffff")
        self.dealine.configure(highlightbackground="#ffffff")
        self.dealine.configure(highlightcolor="black")

        self.get_deadline = tk.Text(self.dealine)
        self.get_deadline.place(relx=0.065, rely=0.364, relheight=0.455
                , relwidth=0.871, bordermode='ignore')
        self.get_deadline.configure(background="white")
        self.get_deadline.configure(font="TkTextFont")
        self.get_deadline.configure(foreground="black")
        self.get_deadline.configure(highlightbackground="#ffffff")
        self.get_deadline.configure(highlightcolor="black")
        self.get_deadline.configure(insertbackground="black")
        self.get_deadline.configure(selectbackground="blue")
        self.get_deadline.configure(selectforeground="white")
        self.get_deadline.configure(wrap="word")

        self.status = tk.LabelFrame(self.assignment_detail)
        self.status.place(relx=0.515, rely=0.629, relheight=0.314, relwidth=0.456
                , bordermode='ignore')
        self.status.configure(relief='groove')
        self.status.configure(foreground="black")
        self.status.configure(text='''Status''')
        self.status.configure(background="#ffffff")
        self.status.configure(highlightbackground="#ffffff")
        self.status.configure(highlightcolor="black")

        self.get_status = tk.Text(self.status)
        self.get_status.place(relx=0.065, rely=0.364, relheight=0.455
                , relwidth=0.871, bordermode='ignore')
        self.get_status.configure(background="white")
        self.get_status.configure(font="TkTextFont")
        self.get_status.configure(foreground="black")
        self.get_status.configure(highlightbackground="#ffffff")
        self.get_status.configure(highlightcolor="black")
        self.get_status.configure(insertbackground="black")
        self.get_status.configure(selectbackground="blue")
        self.get_status.configure(selectforeground="white")
        self.get_status.configure(wrap="word")

        self.back_butt = tk.Button(self.main_assignment)
        self.back_butt.place(relx=0.388, rely=0.89, height=30, width=60
                , bordermode='ignore')
        self.back_butt.configure(activebackground="#05bff5")
        self.back_butt.configure(activeforeground="white")
        self.back_butt.configure(background="#ffffff")
        self.back_butt.configure(disabledforeground="#bfbfbf")
        self.back_butt.configure(font="-family {Arcon Rounded-} -size 10 -weight bold")
        self.back_butt.configure(foreground="#05bff5")
        self.back_butt.configure(highlightbackground="#ffffff")
        self.back_butt.configure(highlightcolor="black")
        self.back_butt.configure(pady="0")
        self.back_butt.configure(text='''back''')

        self.alert = tk.Button(self.main_assignment)
        self.alert.place(relx=0.509, rely=0.89, height=30, width=60
                , bordermode='ignore')
        self.alert.configure(activebackground="#05bff5")
        self.alert.configure(activeforeground="white")
        self.alert.configure(background="#ffffff")
        self.alert.configure(disabledforeground="#bfbfbf")
        self.alert.configure(font="-family {Arcon Rounded-} -size 10 -weight bold")
        self.alert.configure(foreground="#05bff5")
        self.alert.configure(highlightbackground="#ffffff")
        self.alert.configure(highlightcolor="black")
        self.alert.configure(pady="0")
        self.alert.configure(text='''alert''')

if __name__ == '__main__':
    vp_start_gui()





