#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Nov 28, 2020 02:29:04 PM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top45 {base} {
    global vTcl
    if {$base == ""} {
        set base .top45
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m71" -background $vTcl(pr,menubgcolor) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x540+255+100
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Register"
    vTcl:DefineAlias "$top" "register" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #ff8000 \
        -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Arcon Rounded-} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -justify left -text {Buku Penghubung} 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "register" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -borderwidth 0 -disabledforeground #ffffff \
        -font {-family {Arcon Rounded-} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Create Account} 
    vTcl:DefineAlias "$top.lab47" "create_account" vTcl:WidgetProc "register" 1
    checkbutton $top.che48 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #05bff5 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #05bff5 \
        -highlightcolor #ffffff -justify left -selectcolor #05bff5 \
        -text Student -variable che48 
    vTcl:DefineAlias "$top.che48" "student" vTcl:WidgetProc "register" 1
    checkbutton $top.che49 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #05bff5 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #05bff5 \
        -highlightcolor white -justify left -selectcolor #05bff5 \
        -text Teacher -variable che49 
    vTcl:DefineAlias "$top.che49" "teacher" vTcl:WidgetProc "register" 1
    checkbutton $top.che50 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #05bff5 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #05bff5 \
        -highlightcolor white -justify left -selectcolor #05bff5 \
        -text Parents -variable che50 
    vTcl:DefineAlias "$top.che50" "parents" vTcl:WidgetProc "register" 1
    entry $top.ent51 \
        -background white -disabledbackground white -disabledforeground black \
        -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #05bff5 -highlightcolor black \
        -insertbackground white -readonlybackground white \
        -selectbackground #05bff5 -selectforeground white -textvariable name \
        -width 10 
    vTcl:DefineAlias "$top.ent51" "entry_name" vTcl:WidgetProc "register" 1
    entry $top.ent52 \
        -background white -disabledbackground white -disabledforeground black \
        -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #05bff5 -highlightcolor black \
        -insertbackground white -readonlybackground white \
        -selectbackground #05bff5 -selectforeground white \
        -textvariable username -width 10 
    vTcl:DefineAlias "$top.ent52" "entry_username" vTcl:WidgetProc "register" 1
    entry $top.ent57 \
        -background white -disabledbackground white -disabledforeground black \
        -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #05bff5 -highlightcolor black \
        -insertbackground white -readonlybackground white \
        -selectbackground #05bff5 -selectforeground white \
        -textvariable phone_number -width 10 
    vTcl:DefineAlias "$top.ent57" "entry_phone_number" vTcl:WidgetProc "register" 1
    entry $top.ent58 \
        -background white -disabledbackground white -disabledforeground black \
        -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #05bff5 -highlightcolor black \
        -insertbackground black -readonlybackground white \
        -selectbackground #05bff5 -selectforeground white \
        -textvariable address -width 10 
    vTcl:DefineAlias "$top.ent58" "entry_address" vTcl:WidgetProc "register" 1
    entry $top.ent59 \
        -background white -disabledbackground white -disabledforeground black \
        -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #05bff5 -highlightcolor black \
        -insertbackground black -readonlybackground white \
        -selectbackground #05bff5 -selectforeground white -textvariable email \
        -width 10 
    vTcl:DefineAlias "$top.ent59" "entry_email" vTcl:WidgetProc "register" 1
    entry $top.ent60 \
        -background white -disabledbackground white -disabledforeground black \
        -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #05bff5 -highlightcolor black \
        -insertbackground white -readonlybackground white \
        -selectbackground #05bff5 -selectforeground white \
        -textvariable password -width 10 
    vTcl:DefineAlias "$top.ent60" "entry_password" vTcl:WidgetProc "register" 1
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {MY ROLE                  :} 
    vTcl:DefineAlias "$top.lab62" "my_role" vTcl:WidgetProc "register" 1
    label $top.lab64 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {NAME                       :} 
    vTcl:DefineAlias "$top.lab64" "name" vTcl:WidgetProc "register" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {USERNAME             :} 
    vTcl:DefineAlias "$top.lab65" "username" vTcl:WidgetProc "register" 1
    label $top.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {PHONE NUMBER   :} 
    vTcl:DefineAlias "$top.lab66" "phone_number" vTcl:WidgetProc "register" 1
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ADDRESS                :} 
    vTcl:DefineAlias "$top.lab67" "address" vTcl:WidgetProc "register" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {EMAIL                      :} 
    vTcl:DefineAlias "$top.lab68" "email" vTcl:WidgetProc "register" 1
    label $top.lab69 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {PASSWORD           :} 
    vTcl:DefineAlias "$top.lab69" "password" vTcl:WidgetProc "register" 1
    button $top.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #05bff5 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text REGISTER 
    vTcl:DefineAlias "$top.but70" "butt_register" vTcl:WidgetProc "register" 1
    menu $top.m71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #05bff5 \
        -disabledforeground #a3a3a3 \
        -font {-family {Arcon Rounded-} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Buku Penghubung} 
    vTcl:DefineAlias "$top.lab48" "Label2" vTcl:WidgetProc "register" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx -0.517 -y 0 -rely -0.148 -width 0 -relwidth 1 \
        -height 0 -relheight 0.056 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.13 -width 0 -relwidth 0.5 \
        -height 0 -relheight 0.111 -anchor nw -bordermode ignore 
    place $top.che48 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.296 -width 0 -relwidth 0.133 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.che49 \
        -in $top -x 0 -relx 0.483 -y 0 -rely 0.296 -width 0 -relwidth 0.133 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.che50 \
        -in $top -x 0 -relx 0.633 -y 0 -rely 0.296 -width 0 -relwidth 0.133 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.ent51 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.37 -width 320 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent52 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.444 -width 320 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.519 -width 320 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.593 -width 320 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.667 -width 320 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.741 -width 320 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.296 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.37 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.444 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.519 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.593 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.667 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.741 -width 0 -relwidth 0.2 \
        -height 0 -relheight 0.046 -anchor nw -bordermode ignore 
    place $top.but70 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.852 -width 120 -relwidth 0 \
        -height 25 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 0.056 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top45 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

