#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 28, 2020 02:34:41 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Register_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Register_support.set_Tk_var()
    top = register (root)
    Register_support.init(root, top)
    root.mainloop()

w = None
def create_register(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_register(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Register_support.set_Tk_var()
    top = register (w)
    Register_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_register():
    global w
    w.destroy()
    w = None

class register:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x540+255+100")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Register")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=-0.517, rely=-0.148, height=30, width=600)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ff8000")
        self.Label1.configure(borderwidth="0")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Arcon Rounded-} -size 10 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(justify='left')
        self.Label1.configure(text='''Buku Penghubung''')

        self.create_account = tk.Label(top)
        self.create_account.place(relx=0.25, rely=0.13, height=60, width=300)
        self.create_account.configure(activebackground="#f9f9f9")
        self.create_account.configure(activeforeground="black")
        self.create_account.configure(background="#ffffff")
        self.create_account.configure(borderwidth="0")
        self.create_account.configure(disabledforeground="#ffffff")
        self.create_account.configure(font="-family {Arcon Rounded-} -size 24 -weight bold")
        self.create_account.configure(foreground="#05bff5")
        self.create_account.configure(highlightbackground="#d9d9d9")
        self.create_account.configure(highlightcolor="black")
        self.create_account.configure(text='''Create Account''')

        self.student = tk.Checkbutton(top)
        self.student.place(relx=0.333, rely=0.296, relheight=0.046
                , relwidth=0.133)
        self.student.configure(activebackground="#ffffff")
        self.student.configure(activeforeground="#000000")
        self.student.configure(background="#ffffff")
        self.student.configure(disabledforeground="#05bff5")
        self.student.configure(foreground="#000000")
        self.student.configure(highlightbackground="#05bff5")
        self.student.configure(highlightcolor="#ffffff")
        self.student.configure(justify='left')
        self.student.configure(selectcolor="#05bff5")
        self.student.configure(text='''Student''')
        self.student.configure(variable=Register_support.che48)

        self.teacher = tk.Checkbutton(top)
        self.teacher.place(relx=0.483, rely=0.296, relheight=0.046
                , relwidth=0.133)
        self.teacher.configure(activebackground="#ffffff")
        self.teacher.configure(activeforeground="#000000")
        self.teacher.configure(background="#ffffff")
        self.teacher.configure(disabledforeground="#05bff5")
        self.teacher.configure(foreground="#000000")
        self.teacher.configure(highlightbackground="#05bff5")
        self.teacher.configure(highlightcolor="white")
        self.teacher.configure(justify='left')
        self.teacher.configure(selectcolor="#05bff5")
        self.teacher.configure(text='''Teacher''')
        self.teacher.configure(variable=Register_support.che49)

        self.parents = tk.Checkbutton(top)
        self.parents.place(relx=0.633, rely=0.296, relheight=0.046
                , relwidth=0.133)
        self.parents.configure(activebackground="#ffffff")
        self.parents.configure(activeforeground="#000000")
        self.parents.configure(background="#ffffff")
        self.parents.configure(disabledforeground="#05bff5")
        self.parents.configure(font="-family {Segoe UI} -size 9")
        self.parents.configure(foreground="#000000")
        self.parents.configure(highlightbackground="#05bff5")
        self.parents.configure(highlightcolor="white")
        self.parents.configure(justify='left')
        self.parents.configure(selectcolor="#05bff5")
        self.parents.configure(text='''Parents''')
        self.parents.configure(variable=Register_support.che50)

        self.entry_name = tk.Entry(top)
        self.entry_name.place(relx=0.333, rely=0.37, height=25, relwidth=0.533)
        self.entry_name.configure(background="white")
        self.entry_name.configure(disabledbackground="white")
        self.entry_name.configure(disabledforeground="black")
        self.entry_name.configure(font="TkFixedFont")
        self.entry_name.configure(foreground="#000000")
        self.entry_name.configure(highlightbackground="#05bff5")
        self.entry_name.configure(highlightcolor="black")
        self.entry_name.configure(insertbackground="white")
        self.entry_name.configure(readonlybackground="white")
        self.entry_name.configure(selectbackground="#05bff5")
        self.entry_name.configure(selectforeground="white")
        self.entry_name.configure(textvariable=Register_support.name)

        self.entry_username = tk.Entry(top)
        self.entry_username.place(relx=0.333, rely=0.444, height=25
                , relwidth=0.533)
        self.entry_username.configure(background="white")
        self.entry_username.configure(disabledbackground="white")
        self.entry_username.configure(disabledforeground="black")
        self.entry_username.configure(font="TkFixedFont")
        self.entry_username.configure(foreground="#000000")
        self.entry_username.configure(highlightbackground="#05bff5")
        self.entry_username.configure(highlightcolor="black")
        self.entry_username.configure(insertbackground="white")
        self.entry_username.configure(readonlybackground="white")
        self.entry_username.configure(selectbackground="#05bff5")
        self.entry_username.configure(selectforeground="white")
        self.entry_username.configure(textvariable=Register_support.username)

        self.entry_phone_number = tk.Entry(top)
        self.entry_phone_number.place(relx=0.333, rely=0.519, height=25
                , relwidth=0.533)
        self.entry_phone_number.configure(background="white")
        self.entry_phone_number.configure(disabledbackground="white")
        self.entry_phone_number.configure(disabledforeground="black")
        self.entry_phone_number.configure(font="TkFixedFont")
        self.entry_phone_number.configure(foreground="#000000")
        self.entry_phone_number.configure(highlightbackground="#05bff5")
        self.entry_phone_number.configure(highlightcolor="black")
        self.entry_phone_number.configure(insertbackground="white")
        self.entry_phone_number.configure(readonlybackground="white")
        self.entry_phone_number.configure(selectbackground="#05bff5")
        self.entry_phone_number.configure(selectforeground="white")
        self.entry_phone_number.configure(textvariable=Register_support.phone_number)

        self.entry_address = tk.Entry(top)
        self.entry_address.place(relx=0.333, rely=0.593, height=25
                , relwidth=0.533)
        self.entry_address.configure(background="white")
        self.entry_address.configure(disabledbackground="white")
        self.entry_address.configure(disabledforeground="black")
        self.entry_address.configure(font="TkFixedFont")
        self.entry_address.configure(foreground="#000000")
        self.entry_address.configure(highlightbackground="#05bff5")
        self.entry_address.configure(highlightcolor="black")
        self.entry_address.configure(insertbackground="black")
        self.entry_address.configure(readonlybackground="white")
        self.entry_address.configure(selectbackground="#05bff5")
        self.entry_address.configure(selectforeground="white")
        self.entry_address.configure(textvariable=Register_support.address)

        self.entry_email = tk.Entry(top)
        self.entry_email.place(relx=0.333, rely=0.667, height=25, relwidth=0.533)

        self.entry_email.configure(background="white")
        self.entry_email.configure(disabledbackground="white")
        self.entry_email.configure(disabledforeground="black")
        self.entry_email.configure(font="TkFixedFont")
        self.entry_email.configure(foreground="#000000")
        self.entry_email.configure(highlightbackground="#05bff5")
        self.entry_email.configure(highlightcolor="black")
        self.entry_email.configure(insertbackground="black")
        self.entry_email.configure(readonlybackground="white")
        self.entry_email.configure(selectbackground="#05bff5")
        self.entry_email.configure(selectforeground="white")
        self.entry_email.configure(textvariable=Register_support.email)

        self.entry_password = tk.Entry(top)
        self.entry_password.place(relx=0.333, rely=0.741, height=25
                , relwidth=0.533)
        self.entry_password.configure(background="white")
        self.entry_password.configure(disabledbackground="white")
        self.entry_password.configure(disabledforeground="black")
        self.entry_password.configure(font="TkFixedFont")
        self.entry_password.configure(foreground="#000000")
        self.entry_password.configure(highlightbackground="#05bff5")
        self.entry_password.configure(highlightcolor="black")
        self.entry_password.configure(insertbackground="white")
        self.entry_password.configure(readonlybackground="white")
        self.entry_password.configure(selectbackground="#05bff5")
        self.entry_password.configure(selectforeground="white")
        self.entry_password.configure(textvariable=Register_support.password)

        self.my_role = tk.Label(top)
        self.my_role.place(relx=0.1, rely=0.296, height=25, width=120)
        self.my_role.configure(activebackground="#f9f9f9")
        self.my_role.configure(activeforeground="black")
        self.my_role.configure(background="#ffffff")
        self.my_role.configure(disabledforeground="#a3a3a3")
        self.my_role.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.my_role.configure(foreground="#000000")
        self.my_role.configure(highlightbackground="#d9d9d9")
        self.my_role.configure(highlightcolor="black")
        self.my_role.configure(text='''MY ROLE                  :''')

        self.name = tk.Label(top)
        self.name.place(relx=0.1, rely=0.37, height=25, width=120)
        self.name.configure(activebackground="#f9f9f9")
        self.name.configure(activeforeground="black")
        self.name.configure(background="#ffffff")
        self.name.configure(disabledforeground="#a3a3a3")
        self.name.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.name.configure(foreground="#000000")
        self.name.configure(highlightbackground="#d9d9d9")
        self.name.configure(highlightcolor="black")
        self.name.configure(text='''NAME                       :''')

        self.username = tk.Label(top)
        self.username.place(relx=0.1, rely=0.444, height=25, width=120)
        self.username.configure(activebackground="#f9f9f9")
        self.username.configure(activeforeground="black")
        self.username.configure(background="#ffffff")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(text='''USERNAME             :''')

        self.phone_number = tk.Label(top)
        self.phone_number.place(relx=0.1, rely=0.519, height=25, width=120)
        self.phone_number.configure(activebackground="#f9f9f9")
        self.phone_number.configure(activeforeground="black")
        self.phone_number.configure(background="#ffffff")
        self.phone_number.configure(disabledforeground="#a3a3a3")
        self.phone_number.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.phone_number.configure(foreground="#000000")
        self.phone_number.configure(highlightbackground="#d9d9d9")
        self.phone_number.configure(highlightcolor="black")
        self.phone_number.configure(text='''PHONE NUMBER   :''')

        self.address = tk.Label(top)
        self.address.place(relx=0.1, rely=0.593, height=25, width=120)
        self.address.configure(activebackground="#f9f9f9")
        self.address.configure(activeforeground="black")
        self.address.configure(background="#ffffff")
        self.address.configure(disabledforeground="#a3a3a3")
        self.address.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.address.configure(foreground="#000000")
        self.address.configure(highlightbackground="#d9d9d9")
        self.address.configure(highlightcolor="black")
        self.address.configure(text='''ADDRESS                :''')

        self.email = tk.Label(top)
        self.email.place(relx=0.1, rely=0.667, height=25, width=120)
        self.email.configure(activebackground="#f9f9f9")
        self.email.configure(activeforeground="black")
        self.email.configure(background="#ffffff")
        self.email.configure(disabledforeground="#a3a3a3")
        self.email.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.email.configure(foreground="#000000")
        self.email.configure(highlightbackground="#d9d9d9")
        self.email.configure(highlightcolor="black")
        self.email.configure(text='''EMAIL                      :''')

        self.password = tk.Label(top)
        self.password.place(relx=0.1, rely=0.741, height=25, width=120)
        self.password.configure(activebackground="#f9f9f9")
        self.password.configure(activeforeground="black")
        self.password.configure(background="#ffffff")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(text='''PASSWORD           :''')

        self.butt_register = tk.Button(top)
        self.butt_register.place(relx=0.4, rely=0.852, height=25, width=120)
        self.butt_register.configure(activebackground="#ececec")
        self.butt_register.configure(activeforeground="#000000")
        self.butt_register.configure(background="#05bff5")
        self.butt_register.configure(disabledforeground="#a3a3a3")
        self.butt_register.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.butt_register.configure(foreground="#ffffff")
        self.butt_register.configure(highlightbackground="#d9d9d9")
        self.butt_register.configure(highlightcolor="black")
        self.butt_register.configure(pady="0")
        self.butt_register.configure(text='''REGISTER''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg='#ffffff',fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.0, rely=0.0, height=30, width=600)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#05bff5")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Arcon Rounded-} -size 10 -weight bold")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Buku Penghubung''')

if __name__ == '__main__':
    vp_start_gui()





