#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Dec 03, 2020 09:24:21 PM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 480x364+654+111
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 729
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Student - Add Submission"
    vTcl:DefineAlias "$top" "student_add submission" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground #ffffff -activeforeground #05bff5 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground #05bff5 -tearoff 0 
    frame $top.fra49 \
        -borderwidth 2 -background #05bff5 -height 30 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 605 
    vTcl:DefineAlias "$top.fra49" "navbar" vTcl:WidgetProc "student_add submission" 1
    set site_3_0 $top.fra49
    label $site_3_0.lab55 \
        -activebackground #05bff5 -activeforeground white -background #05bff5 \
        -disabledforeground black \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground white -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Buku Penghubung} 
    vTcl:DefineAlias "$site_3_0.lab55" "app_name" vTcl:WidgetProc "student_add submission" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.248 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    labelframe $top.lab57 \
        -borderwidth 4 \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground black -relief flat -text {Add Submission} \
        -background white -height 320 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 460 
    vTcl:DefineAlias "$top.lab57" "main" vTcl:WidgetProc "student_add submission" 1
    set site_3_0 $top.lab57
    labelframe $site_3_0.lab58 \
        -font TkDefaultFont -foreground black -text {Assignment Name} \
        -background $vTcl(actual_gui_bg) -height 61 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 310 
    vTcl:DefineAlias "$site_3_0.lab58" "assignment_name" vTcl:WidgetProc "student_add submission" 1
    set site_4_0 $site_3_0.lab58
    text $site_4_0.tex51 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 -wrap word 
    $site_4_0.tex51 configure -font "TkTextFont"
    $site_4_0.tex51 insert end text
    vTcl:DefineAlias "$site_4_0.tex51" "get_assignment_name" vTcl:WidgetProc "student_add submission" 1
    place $site_4_0.tex51 \
        -in $site_4_0 -x 10 -y 20 -width 290 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but63 \
        -activebackground #05bff5 -activeforeground white -background white \
        -disabledforeground #bfbfbf \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text submit 
    vTcl:DefineAlias "$site_3_0.but63" "submit_butt" vTcl:WidgetProc "student_add submission" 1
    labelframe $site_3_0.lab47 \
        -font TkDefaultFont -foreground black -text {Submission File} \
        -background $vTcl(actual_gui_bg) -height 85 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 310 
    vTcl:DefineAlias "$site_3_0.lab47" "submission_file" vTcl:WidgetProc "student_add submission" 1
    set site_4_0 $site_3_0.lab47
    text $site_4_0.tex45 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 -wrap word 
    $site_4_0.tex45 configure -font "TkTextFont"
    $site_4_0.tex45 insert end text
    vTcl:DefineAlias "$site_4_0.tex45" "get_submission_file_name" vTcl:WidgetProc "student_add submission" 1
    button $site_4_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #bfbfbf \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Add File} 
    vTcl:DefineAlias "$site_4_0.but46" "add_butt" vTcl:WidgetProc "student_add submission" 1
    place $site_4_0.tex45 \
        -in $site_4_0 -x 10 -y 20 -width 290 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but46 \
        -in $site_4_0 -x 245 -y 55 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 75 -y 75 -width 310 -relwidth 0 -height 61 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 200 -y 260 -width 60 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 75 -y 140 -width 310 -relwidth 0 -height 85 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra49 \
        -in $top -x 0 -y 0 -width 480 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 10 -y 35 -width 460 -relwidth 0 -height 320 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

