#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Dec 03, 2020 09:24:25 PM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Student - Add Submission_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = student_add_submission (root)
    Student - Add Submission_support.init(root, top)
    root.mainloop()

w = None
def create_student_add_submission(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_student_add_submission(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = student_add_submission (w)
    Student - Add Submission_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_student_add_submission():
    global w
    w.destroy()
    w = None

class student_add_submission:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("480x364+654+111")
        top.minsize(120, 1)
        top.maxsize(1370, 729)
        top.resizable(1,  1)
        top.title("Student - Add Submission")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#ffffff")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg='#05bff5')
        top.configure(menu = self.menubar)

        self.navbar = tk.Frame(top)
        self.navbar.place(relx=0.0, rely=0.0, relheight=0.082, relwidth=1.0)
        self.navbar.configure(relief='flat')
        self.navbar.configure(borderwidth="2")
        self.navbar.configure(background="#05bff5")
        self.navbar.configure(highlightbackground="#ffffff")
        self.navbar.configure(highlightcolor="black")

        self.app_name = tk.Label(self.navbar)
        self.app_name.place(relx=0.0, rely=0.0, height=30, width=119)
        self.app_name.configure(activebackground="#05bff5")
        self.app_name.configure(activeforeground="white")
        self.app_name.configure(background="#05bff5")
        self.app_name.configure(disabledforeground="black")
        self.app_name.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.app_name.configure(foreground="white")
        self.app_name.configure(highlightbackground="#ffffff")
        self.app_name.configure(highlightcolor="black")
        self.app_name.configure(text='''Buku Penghubung''')

        self.main = tk.LabelFrame(top)
        self.main.place(relx=0.021, rely=0.096, relheight=0.879, relwidth=0.958)
        self.main.configure(relief='flat')
        self.main.configure(borderwidth="4")
        self.main.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.main.configure(foreground="black")
        self.main.configure(relief="flat")
        self.main.configure(text='''Add Submission''')
        self.main.configure(background="white")
        self.main.configure(highlightbackground="#ffffff")
        self.main.configure(highlightcolor="black")

        self.assignment_name = tk.LabelFrame(self.main)
        self.assignment_name.place(relx=0.163, rely=0.234, relheight=0.191
                , relwidth=0.674, bordermode='ignore')
        self.assignment_name.configure(relief='groove')
        self.assignment_name.configure(foreground="black")
        self.assignment_name.configure(text='''Assignment Name''')
        self.assignment_name.configure(background="#ffffff")
        self.assignment_name.configure(highlightbackground="#ffffff")
        self.assignment_name.configure(highlightcolor="black")

        self.get_assignment_name = tk.Text(self.assignment_name)
        self.get_assignment_name.place(relx=0.032, rely=0.328, relheight=0.492
                , relwidth=0.935, bordermode='ignore')
        self.get_assignment_name.configure(background="white")
        self.get_assignment_name.configure(font="TkTextFont")
        self.get_assignment_name.configure(foreground="black")
        self.get_assignment_name.configure(highlightbackground="#ffffff")
        self.get_assignment_name.configure(highlightcolor="black")
        self.get_assignment_name.configure(insertbackground="black")
        self.get_assignment_name.configure(selectbackground="blue")
        self.get_assignment_name.configure(selectforeground="white")
        self.get_assignment_name.configure(wrap="word")

        self.submit_butt = tk.Button(self.main)
        self.submit_butt.place(relx=0.435, rely=0.813, height=30, width=60
                , bordermode='ignore')
        self.submit_butt.configure(activebackground="#05bff5")
        self.submit_butt.configure(activeforeground="white")
        self.submit_butt.configure(background="white")
        self.submit_butt.configure(disabledforeground="#bfbfbf")
        self.submit_butt.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.submit_butt.configure(foreground="#05bff5")
        self.submit_butt.configure(highlightbackground="#ffffff")
        self.submit_butt.configure(highlightcolor="black")
        self.submit_butt.configure(pady="0")
        self.submit_butt.configure(relief="sunken")
        self.submit_butt.configure(state='active')
        self.submit_butt.configure(text='''submit''')

        self.submission_file = tk.LabelFrame(self.main)
        self.submission_file.place(relx=0.163, rely=0.438, relheight=0.266
                , relwidth=0.674, bordermode='ignore')
        self.submission_file.configure(relief='groove')
        self.submission_file.configure(foreground="black")
        self.submission_file.configure(text='''Submission File''')
        self.submission_file.configure(background="#ffffff")
        self.submission_file.configure(highlightbackground="#ffffff")
        self.submission_file.configure(highlightcolor="black")

        self.get_submission_file_name = tk.Text(self.submission_file)
        self.get_submission_file_name.place(relx=0.032, rely=0.235
                , relheight=0.353, relwidth=0.935, bordermode='ignore')
        self.get_submission_file_name.configure(background="white")
        self.get_submission_file_name.configure(font="TkTextFont")
        self.get_submission_file_name.configure(foreground="black")
        self.get_submission_file_name.configure(highlightbackground="#ffffff")
        self.get_submission_file_name.configure(highlightcolor="black")
        self.get_submission_file_name.configure(insertbackground="black")
        self.get_submission_file_name.configure(selectbackground="blue")
        self.get_submission_file_name.configure(selectforeground="white")
        self.get_submission_file_name.configure(wrap="word")

        self.add_butt = tk.Button(self.submission_file)
        self.add_butt.place(relx=0.79, rely=0.647, height=24, width=54
                , bordermode='ignore')
        self.add_butt.configure(activebackground="#ececec")
        self.add_butt.configure(activeforeground="#000000")
        self.add_butt.configure(background="#ffffff")
        self.add_butt.configure(disabledforeground="#bfbfbf")
        self.add_butt.configure(foreground="#000000")
        self.add_butt.configure(highlightbackground="#ffffff")
        self.add_butt.configure(highlightcolor="black")
        self.add_butt.configure(pady="0")
        self.add_butt.configure(text='''Add File''')

if __name__ == '__main__':
    vp_start_gui()





