#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 30, 2020 08:30:01 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Student - Home_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = student_home (root)
    Student - Home_support.init(root, top)
    root.mainloop()

w = None
def create_student_home(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_student_home(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = student_home (w)
    Student - Home_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_student_home():
    global w
    w.destroy()
    w = None

class student_home:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x540+654+111")
        top.minsize(120, 1)
        top.maxsize(1370, 729)
        top.resizable(1,  1)
        top.title("Student - Home")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#ffffff")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg='#05bff5')
        top.configure(menu = self.menubar)

        self.navbar = tk.Frame(top)
        self.navbar.place(relx=0.0, rely=0.0, relheight=0.056, relwidth=1.0)
        self.navbar.configure(background="#05bff5")
        self.navbar.configure(highlightbackground="#ffffff")
        self.navbar.configure(highlightcolor="black")

        self.logout_butt = tk.Button(self.navbar)
        self.logout_butt.place(relx=0.9, rely=0.0, height=30, width=60)
        self.logout_butt.configure(activebackground="white")
        self.logout_butt.configure(activeforeground="#000000")
        self.logout_butt.configure(background="white")
        self.logout_butt.configure(borderwidth="0")
        self.logout_butt.configure(disabledforeground="black")
        self.logout_butt.configure(font="-family {Arcon Rounded-} -size 9")
        self.logout_butt.configure(foreground="#05bff5")
        self.logout_butt.configure(highlightbackground="#ffffff")
        self.logout_butt.configure(highlightcolor="black")
        self.logout_butt.configure(pady="0")
        self.logout_butt.configure(relief="flat")
        self.logout_butt.configure(text='''Logout''')

        self.Label1 = tk.Label(self.navbar)
        self.Label1.place(relx=0.0, rely=0.0, height=30, width=120)
        self.Label1.configure(activebackground="#05bff5")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(background="#05bff5")
        self.Label1.configure(borderwidth="0")
        self.Label1.configure(disabledforeground="black")
        self.Label1.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.Label1.configure(foreground="white")
        self.Label1.configure(highlightbackground="#ffffff")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Buku Penghubung''')

        self.main_home = tk.Frame(top)
        self.main_home.place(relx=0.0, rely=0.054, relheight=0.944, relwidth=1.0)

        self.main_home.configure(relief='flat')
        self.main_home.configure(borderwidth="2")
        self.main_home.configure(background="#ffffff")
        self.main_home.configure(highlightbackground="#ffffff")
        self.main_home.configure(highlightcolor="black")

        self.greetings = tk.Label(self.main_home)
        self.greetings.place(relx=0.0, rely=0.0, height=160, width=600)
        self.greetings.configure(activebackground="white")
        self.greetings.configure(activeforeground="#bbbbbb")
        self.greetings.configure(background="#ffffff")
        self.greetings.configure(borderwidth="0")
        self.greetings.configure(disabledforeground="black")
        self.greetings.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.greetings.configure(foreground="#bbbbbb")
        self.greetings.configure(highlightbackground="#ffffff")
        self.greetings.configure(highlightcolor="black")
        self.greetings.configure(text='''Hi, Name!''')

        self.my_profile = tk.Button(self.main_home)
        self.my_profile.place(relx=0.0, rely=0.314, height=150, width=200)
        self.my_profile.configure(activebackground="white")
        self.my_profile.configure(activeforeground="#05bff5")
        self.my_profile.configure(background="#05bff5")
        self.my_profile.configure(disabledforeground="black")
        self.my_profile.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.my_profile.configure(foreground="white")
        self.my_profile.configure(highlightbackground="#ffffff")
        self.my_profile.configure(highlightcolor="black")
        self.my_profile.configure(pady="0")
        self.my_profile.configure(text='''My Profile''')

        self.my_classes = tk.Button(self.main_home)
        self.my_classes.place(relx=0.333, rely=0.314, height=150, width=200)
        self.my_classes.configure(activebackground="#05bff5")
        self.my_classes.configure(activeforeground="white")
        self.my_classes.configure(background="white")
        self.my_classes.configure(disabledforeground="black")
        self.my_classes.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.my_classes.configure(foreground="#05bff5")
        self.my_classes.configure(highlightbackground="#ffffff")
        self.my_classes.configure(highlightcolor="black")
        self.my_classes.configure(pady="0")
        self.my_classes.configure(text='''My Classes''')

        self.my_assignments = tk.Button(self.main_home)
        self.my_assignments.place(relx=0.667, rely=0.314, height=150, width=200)
        self.my_assignments.configure(activebackground="white")
        self.my_assignments.configure(activeforeground="#05bff5")
        self.my_assignments.configure(background="#05bff5")
        self.my_assignments.configure(disabledforeground="black")
        self.my_assignments.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.my_assignments.configure(foreground="white")
        self.my_assignments.configure(highlightbackground="#ffffff")
        self.my_assignments.configure(highlightcolor="#000000")
        self.my_assignments.configure(pady="0")
        self.my_assignments.configure(text='''My Assignments''')

        self.add_class = tk.Button(self.main_home)
        self.add_class.place(relx=0.0, rely=0.608, height=150, width=200)
        self.add_class.configure(activebackground="#05bff5")
        self.add_class.configure(activeforeground="white")
        self.add_class.configure(background="white")
        self.add_class.configure(disabledforeground="black")
        self.add_class.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.add_class.configure(foreground="#05bff5")
        self.add_class.configure(highlightbackground="#ffffff")
        self.add_class.configure(highlightcolor="black")
        self.add_class.configure(pady="0")
        self.add_class.configure(text='''Add Class''')

        self.faq = tk.Button(self.main_home)
        self.faq.place(relx=0.333, rely=0.608, height=150, width=200)
        self.faq.configure(activebackground="white")
        self.faq.configure(activeforeground="#05bff5")
        self.faq.configure(background="#05bff5")
        self.faq.configure(disabledforeground="black")
        self.faq.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.faq.configure(foreground="white")
        self.faq.configure(highlightbackground="#ffffff")
        self.faq.configure(highlightcolor="black")
        self.faq.configure(pady="0")
        self.faq.configure(text='''FAQ''')

        self.help = tk.Button(self.main_home)
        self.help.place(relx=0.667, rely=0.608, height=150, width=200)
        self.help.configure(activebackground="#05bff5")
        self.help.configure(activeforeground="white")
        self.help.configure(background="white")
        self.help.configure(disabledforeground="black")
        self.help.configure(font="-family {Segoe UI} -size 10 -underline 1")
        self.help.configure(foreground="#05bff5")
        self.help.configure(highlightbackground="#ffffff")
        self.help.configure(highlightcolor="black")
        self.help.configure(pady="0")
        self.help.configure(text='''Help''')

        self.quotes = tk.Label(self.main_home)
        self.quotes.place(relx=0.0, rely=0.902, height=50, width=600)
        self.quotes.configure(activebackground="white")
        self.quotes.configure(activeforeground="#05bff5")
        self.quotes.configure(background="white")
        self.quotes.configure(borderwidth="0")
        self.quotes.configure(disabledforeground="black")
        self.quotes.configure(foreground="#05bff5")
        self.quotes.configure(highlightbackground="#ffffff")
        self.quotes.configure(highlightcolor="black")
        self.quotes.configure(text='''indeed with hardship will be ease''')

if __name__ == '__main__':
    vp_start_gui()





