#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Nov 30, 2020 03:01:24 PM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #ffffff
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ffffff
set vTcl(actual_gui_menu_analog) #ffffff
set vTcl(actual_gui_menu_bg) #ffffff
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ffffff
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x540+654+111
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 729
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Teacher - Home"
    vTcl:DefineAlias "$top" "teacher_home" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground #ffffff -activeforeground #05bff5 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground #05bff5 -tearoff 0 
    frame $top.fra49 \
        -background #05bff5 -height 35 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 605 
    vTcl:DefineAlias "$top.fra49" "navbar" vTcl:WidgetProc "teacher_home" 1
    set site_3_0 $top.fra49
    button $site_3_0.but51 \
        -activebackground white -activeforeground #000000 -background white \
        -borderwidth 0 -disabledforeground black \
        -font {-family {Arcon Rounded-} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -relief flat -text Logout 
    vTcl:DefineAlias "$site_3_0.but51" "logout_butt" vTcl:WidgetProc "teacher_home" 1
    label $site_3_0.lab45 \
        -activebackground #05bff5 -activeforeground white -background #05bff5 \
        -borderwidth 0 -disabledforeground black \
        -font {-family {Arcon Rounded-} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground white -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Buku Penghubung} 
    vTcl:DefineAlias "$site_3_0.lab45" "app_name" vTcl:WidgetProc "teacher_home" 1
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.9 -y 0 -width 60 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.2 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.fra46" "main_home" vTcl:WidgetProc "teacher_home" 1
    set site_3_0 $top.fra46
    label $site_3_0.lab47 \
        -activebackground white -activeforeground #bbbbbb \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground black \
        -font {-family {Segoe UI} -size 18 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #bbbbbb -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {Hi, Name!} 
    vTcl:DefineAlias "$site_3_0.lab47" "greetings" vTcl:WidgetProc "teacher_home" 1
    button $site_3_0.but48 \
        -activebackground white -activeforeground #05bff5 -background #05bff5 \
        -disabledforeground black \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 1 -overstrike 0} \
        -foreground white -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text {My Profile} 
    vTcl:DefineAlias "$site_3_0.but48" "my_profile" vTcl:WidgetProc "teacher_home" 1
    button $site_3_0.but49 \
        -activebackground #05bff5 -activeforeground white -background white \
        -disabledforeground black \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 1 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text {My Classes} 
    vTcl:DefineAlias "$site_3_0.but49" "my_classes" vTcl:WidgetProc "teacher_home" 1
    button $site_3_0.but50 \
        -activebackground white -activeforeground #05bff5 -background #05bff5 \
        -disabledforeground black \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 1 -overstrike 0} \
        -foreground white -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #000000 -pady 0 -text {Assignments List} 
    vTcl:DefineAlias "$site_3_0.but50" "assignments_list" vTcl:WidgetProc "teacher_home" 1
    button $site_3_0.but51 \
        -activebackground #05bff5 -activeforeground white -background white \
        -disabledforeground black \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 1 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text {Create Class} 
    vTcl:DefineAlias "$site_3_0.but51" "create_class" vTcl:WidgetProc "teacher_home" 1
    button $site_3_0.but52 \
        -activebackground white -activeforeground #05bff5 -background #05bff5 \
        -disabledforeground black \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 1 -overstrike 0} \
        -foreground white -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text FAQ 
    vTcl:DefineAlias "$site_3_0.but52" "faq" vTcl:WidgetProc "teacher_home" 1
    button $site_3_0.but53 \
        -activebackground #05bff5 -activeforeground white -background white \
        -disabledforeground black \
        -font {-family {Segoe UI} -size 10 -weight normal -slant roman -underline 1 -overstrike 0} \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Help 
    vTcl:DefineAlias "$site_3_0.but53" "help" vTcl:WidgetProc "teacher_home" 1
    label $site_3_0.lab54 \
        -activebackground white -activeforeground #05bff5 -background white \
        -borderwidth 0 -disabledforeground black -font TkDefaultFont \
        -foreground #05bff5 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {indeed with hardship will be ease} 
    vTcl:DefineAlias "$site_3_0.lab54" "quotes" vTcl:WidgetProc "teacher_home" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 1 -height 0 \
        -relheight 0.313 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -y 0 -rely 0.313 -width 200 -relwidth 0 \
        -height 150 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.333 -y 0 -rely 0.313 -width 200 \
        -relwidth 0 -height 150 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.667 -y 0 -rely 0.313 -width 200 \
        -relwidth 0 -height 150 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -y 0 -rely 0.607 -width 200 -relwidth 0 \
        -height 150 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.333 -y 0 -rely 0.607 -width 200 \
        -relwidth 0 -height 150 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.667 -y 0 -rely 0.607 -width 200 \
        -relwidth 0 -height 150 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -y 0 -rely 0.902 -width 0 -relwidth 1 -height 0 \
        -relheight 0.098 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra49 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 0.056 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -y 0 -rely 0.054 -width 0 -relwidth 1 -height 0 \
        -relheight 0.944 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

