#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Dec 03, 2020 10:48:28 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Teacher - Submission Check_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Teacher - Submission Check_support.set_Tk_var()
    top = teacher_sub_check (root)
    Teacher - Submission Check_support.init(root, top)
    root.mainloop()

w = None
def create_teacher_sub_check(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_teacher_sub_check(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Teacher - Submission Check_support.set_Tk_var()
    top = teacher_sub_check (w)
    Teacher - Submission Check_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_teacher_sub_check():
    global w
    w.destroy()
    w = None

class teacher_sub_check:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x322+613+115")
        top.minsize(120, 1)
        top.maxsize(1370, 729)
        top.resizable(0,  0)
        top.title("Teacher - Submission Check")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#ffffff")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg='#05bff5')
        top.configure(menu = self.menubar)

        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.sub_menu = tk.Menu(top,
                activebackground="white",
                activeborderwidth=1,
                activeforeground="#05bff5",
                background="#ffffff",
                borderwidth=1,
                disabledforeground="#bfbfbf",
                foreground="#05bff5",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                label="Profile")
        self.sub_menu.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="My Profile")
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.sub_menu1 = tk.Menu(top,
                activebackground="#ececec",
                activeborderwidth=1,
                activeforeground="#000000",
                background="#ffffff",
                borderwidth=1,
                disabledforeground="#bfbfbf",
                foreground="#000000",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu1,
                label="Classes")
        self.sub_menu1.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="Create Class")
        self.sub_menu1.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="My Classes")
        self.menubar.add_separator(
)
        self.menubar.add_separator(
)
        self.sub_menu12 = tk.Menu(top,
                activebackground="#ececec",
                activeborderwidth=1,
                activeforeground="#000000",
                background="#ffffff",
                borderwidth=1,
                disabledforeground="#bfbfbf",
                foreground="#000000",
                tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu12,
                label="Assignment")
        self.sub_menu12.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="Add Assignment")
        self.sub_menu12.add_command(
                activebackground="white",
                activeforeground="#05bff5",
                background="white",
                foreground="black",
                label="Assignment List")

        self.navbar = tk.Frame(top)
        self.navbar.place(x=0, y=0, height=28, width=600)
        self.navbar.configure(relief='flat')
        self.navbar.configure(borderwidth="2")
        self.navbar.configure(background="#05bff5")
        self.navbar.configure(highlightbackground="#ffffff")
        self.navbar.configure(highlightcolor="black")

        self.logout_butt = tk.Button(self.navbar)
        self.logout_butt.place(x=540, y=0, height=30, width=60)
        self.logout_butt.configure(activebackground="white")
        self.logout_butt.configure(activeforeground="#000000")
        self.logout_butt.configure(background="white")
        self.logout_butt.configure(disabledforeground="black")
        self.logout_butt.configure(font="-family {Arcon Rounded-} -size 9")
        self.logout_butt.configure(foreground="#05bff5")
        self.logout_butt.configure(highlightbackground="#ffffff")
        self.logout_butt.configure(highlightcolor="black")
        self.logout_butt.configure(pady="0")
        self.logout_butt.configure(relief="flat")
        self.logout_butt.configure(text='''Logout''')

        self.app_name = tk.Label(self.navbar)
        self.app_name.place(x=0, y=0, height=28, width=120)
        self.app_name.configure(activebackground="#05bff5")
        self.app_name.configure(activeforeground="white")
        self.app_name.configure(background="#05bff5")
        self.app_name.configure(disabledforeground="black")
        self.app_name.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.app_name.configure(foreground="white")
        self.app_name.configure(highlightbackground="#ffffff")
        self.app_name.configure(highlightcolor="black")
        self.app_name.configure(text='''Buku Penghubung''')

        self.get_assignment_name = tk.LabelFrame(top)
        self.get_assignment_name.place(x=10, y=33, height=287, width=580)
        self.get_assignment_name.configure(relief='flat')
        self.get_assignment_name.configure(borderwidth="4")
        self.get_assignment_name.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.get_assignment_name.configure(foreground="black")
        self.get_assignment_name.configure(relief="flat")
        self.get_assignment_name.configure(text='''Assignment Name''')
        self.get_assignment_name.configure(background="white")
        self.get_assignment_name.configure(highlightbackground="#ffffff")
        self.get_assignment_name.configure(highlightcolor="black")

        self.back_butt = tk.Button(self.get_assignment_name)
        self.back_butt.place(x=225, y=245, height=30, width=60
                , bordermode='ignore')
        self.back_butt.configure(activebackground="#05bff5")
        self.back_butt.configure(activeforeground="white")
        self.back_butt.configure(background="white")
        self.back_butt.configure(disabledforeground="#bfbfbf")
        self.back_butt.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.back_butt.configure(foreground="#05bff5")
        self.back_butt.configure(highlightbackground="#ffffff")
        self.back_butt.configure(highlightcolor="black")
        self.back_butt.configure(pady="0")
        self.back_butt.configure(text='''back''')

        self.box_student = ScrolledListBox(self.get_assignment_name)
        self.box_student.place(x=19, y=23, height=212, width=193
                , bordermode='ignore')
        self.box_student.configure(background="white")
        self.box_student.configure(cursor="xterm")
        self.box_student.configure(disabledforeground="#bfbfbf")
        self.box_student.configure(font="TkFixedFont")
        self.box_student.configure(foreground="black")
        self.box_student.configure(highlightbackground="#ffffff")
        self.box_student.configure(highlightcolor="#ffffff")
        self.box_student.configure(selectbackground="white")
        self.box_student.configure(selectforeground="#05bff5")
        self.box_student.configure(listvariable=Teacher - Submission Check_support.student_name)

        self.class_detail = tk.Frame(self.get_assignment_name)
        self.class_detail.place(x=222, y=23, height=211, width=338
                , bordermode='ignore')
        self.class_detail.configure(relief='groove')
        self.class_detail.configure(borderwidth="2")
        self.class_detail.configure(relief="groove")
        self.class_detail.configure(background="#ffffff")
        self.class_detail.configure(highlightbackground="#ffffff")
        self.class_detail.configure(highlightcolor="black")

        self.owner_name = tk.LabelFrame(self.class_detail)
        self.owner_name.place(x=10, y=5, height=60, width=320)
        self.owner_name.configure(relief='groove')
        self.owner_name.configure(foreground="black")
        self.owner_name.configure(text='''Name''')
        self.owner_name.configure(background="#ffffff")
        self.owner_name.configure(highlightbackground="#ffffff")
        self.owner_name.configure(highlightcolor="black")

        self.get_student_name = tk.Text(self.owner_name)
        self.get_student_name.place(x=10, y=20, height=30, width=300
                , bordermode='ignore')
        self.get_student_name.configure(background="white")
        self.get_student_name.configure(cursor="fleur")
        self.get_student_name.configure(font="TkTextFont")
        self.get_student_name.configure(foreground="black")
        self.get_student_name.configure(highlightbackground="#ffffff")
        self.get_student_name.configure(highlightcolor="black")
        self.get_student_name.configure(insertbackground="black")
        self.get_student_name.configure(selectbackground="blue")
        self.get_student_name.configure(selectforeground="white")
        self.get_student_name.configure(wrap="word")

        self.deadline = tk.LabelFrame(self.class_detail)
        self.deadline.place(x=10, y=65, height=80, width=320)
        self.deadline.configure(relief='groove')
        self.deadline.configure(foreground="black")
        self.deadline.configure(text='''Submission File''')
        self.deadline.configure(background="#ffffff")
        self.deadline.configure(highlightbackground="#ffffff")
        self.deadline.configure(highlightcolor="black")

        self.get_file_name = tk.Text(self.deadline)
        self.get_file_name.place(x=10, y=20, height=25, width=300
                , bordermode='ignore')
        self.get_file_name.configure(background="white")
        self.get_file_name.configure(cursor="fleur")
        self.get_file_name.configure(font="TkTextFont")
        self.get_file_name.configure(foreground="black")
        self.get_file_name.configure(highlightbackground="#ffffff")
        self.get_file_name.configure(highlightcolor="black")
        self.get_file_name.configure(insertbackground="black")
        self.get_file_name.configure(selectbackground="blue")
        self.get_file_name.configure(selectforeground="white")
        self.get_file_name.configure(wrap="word")

        self.file_butt = tk.Button(self.deadline)
        self.file_butt.place(x=250, y=48, height=25, width=55
                , bordermode='ignore')
        self.file_butt.configure(activebackground="#ececec")
        self.file_butt.configure(activeforeground="#000000")
        self.file_butt.configure(background="#ffffff")
        self.file_butt.configure(disabledforeground="#bfbfbf")
        self.file_butt.configure(foreground="#000000")
        self.file_butt.configure(highlightbackground="#ffffff")
        self.file_butt.configure(highlightcolor="black")
        self.file_butt.configure(pady="0")
        self.file_butt.configure(text='''open file''')

        self.set_score = tk.LabelFrame(self.class_detail)
        self.set_score.place(x=10, y=145, height=60, width=320)
        self.set_score.configure(relief='groove')
        self.set_score.configure(foreground="black")
        self.set_score.configure(text='''Score''')
        self.set_score.configure(background="#ffffff")
        self.set_score.configure(highlightbackground="#ffffff")
        self.set_score.configure(highlightcolor="black")

        self.entry_score = tk.Entry(self.set_score)
        self.entry_score.place(x=10, y=20, height=30, width=300
                , bordermode='ignore')
        self.entry_score.configure(background="white")
        self.entry_score.configure(disabledforeground="#bfbfbf")
        self.entry_score.configure(font="TkFixedFont")
        self.entry_score.configure(foreground="#000000")
        self.entry_score.configure(insertbackground="black")
        self.entry_score.configure(textvariable=Teacher - Submission Check_support.score)

        self.save_butt = tk.Button(self.get_assignment_name)
        self.save_butt.place(x=295, y=245, height=30, width=60
                , bordermode='ignore')
        self.save_butt.configure(activebackground="#05bff5")
        self.save_butt.configure(activeforeground="white")
        self.save_butt.configure(background="white")
        self.save_butt.configure(disabledforeground="#bfbfbf")
        self.save_butt.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.save_butt.configure(foreground="#05bff5")
        self.save_butt.configure(highlightbackground="#ffffff")
        self.save_butt.configure(highlightcolor="black")
        self.save_butt.configure(pady="0")
        self.save_butt.configure(text='''save''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





