#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Dec 03, 2020 09:15:29 AM +07  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Teacher - Create Class_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Teacher - Create Class_support.set_Tk_var()
    top = teacher_create_class (root)
    Teacher - Create Class_support.init(root, top)
    root.mainloop()

w = None
def create_teacher_create_class(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_teacher_create_class(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    Teacher - Create Class_support.set_Tk_var()
    top = teacher_create_class (w)
    Teacher - Create Class_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_teacher_create_class():
    global w
    w.destroy()
    w = None

class teacher_create_class:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'white'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("480x300+654+111")
        top.minsize(120, 1)
        top.maxsize(1370, 729)
        top.resizable(1,  1)
        top.title("Teacher - Create Class")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#ffffff")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg='#05bff5')
        top.configure(menu = self.menubar)

        self.navbar = tk.Frame(top)
        self.navbar.place(relx=0.0, rely=0.0, relheight=0.1, relwidth=1.0)
        self.navbar.configure(relief='flat')
        self.navbar.configure(borderwidth="2")
        self.navbar.configure(background="#05bff5")
        self.navbar.configure(highlightbackground="#ffffff")
        self.navbar.configure(highlightcolor="black")

        self.app_name = tk.Label(self.navbar)
        self.app_name.place(relx=0.0, rely=0.0, height=30, width=119)
        self.app_name.configure(activebackground="#05bff5")
        self.app_name.configure(activeforeground="white")
        self.app_name.configure(background="#05bff5")
        self.app_name.configure(disabledforeground="black")
        self.app_name.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.app_name.configure(foreground="white")
        self.app_name.configure(highlightbackground="#ffffff")
        self.app_name.configure(highlightcolor="black")
        self.app_name.configure(text='''Buku Penghubung''')

        self.create_class = tk.LabelFrame(top)
        self.create_class.place(relx=0.021, rely=0.117, relheight=0.867
                , relwidth=0.958)
        self.create_class.configure(relief='flat')
        self.create_class.configure(borderwidth="4")
        self.create_class.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.create_class.configure(foreground="black")
        self.create_class.configure(relief="flat")
        self.create_class.configure(text='''Create Class''')
        self.create_class.configure(background="white")
        self.create_class.configure(highlightbackground="#ffffff")
        self.create_class.configure(highlightcolor="black")

        self.class_name = tk.LabelFrame(self.create_class)
        self.class_name.place(relx=0.163, rely=0.154, relheight=0.231
                , relwidth=0.674, bordermode='ignore')
        self.class_name.configure(relief='groove')
        self.class_name.configure(foreground="black")
        self.class_name.configure(text='''Class Name''')
        self.class_name.configure(background="#ffffff")
        self.class_name.configure(highlightbackground="#ffffff")
        self.class_name.configure(highlightcolor="black")

        self.entry_class_name = tk.Entry(self.class_name)
        self.entry_class_name.place(relx=0.032, rely=0.333, height=30
                , relwidth=0.935, bordermode='ignore')
        self.entry_class_name.configure(background="white")
        self.entry_class_name.configure(disabledforeground="#bfbfbf")
        self.entry_class_name.configure(font="TkFixedFont")
        self.entry_class_name.configure(foreground="#000000")
        self.entry_class_name.configure(highlightbackground="#ffffff")
        self.entry_class_name.configure(highlightcolor="black")
        self.entry_class_name.configure(insertbackground="black")
        self.entry_class_name.configure(selectbackground="blue")
        self.entry_class_name.configure(selectforeground="white")

        self.enrollment_key = tk.LabelFrame(self.create_class)
        self.enrollment_key.place(relx=0.163, rely=0.385, relheight=0.346
                , relwidth=0.674, bordermode='ignore')
        self.enrollment_key.configure(relief='groove')
        self.enrollment_key.configure(foreground="black")
        self.enrollment_key.configure(text='''Enrollment Key''')
        self.enrollment_key.configure(background="#ffffff")
        self.enrollment_key.configure(highlightbackground="#ffffff")
        self.enrollment_key.configure(highlightcolor="black")

        self.entry_key = tk.Entry(self.enrollment_key)
        self.entry_key.place(relx=0.032, rely=0.556, height=30, relwidth=0.935
                , bordermode='ignore')
        self.entry_key.configure(background="white")
        self.entry_key.configure(disabledforeground="#bfbfbf")
        self.entry_key.configure(font="TkFixedFont")
        self.entry_key.configure(foreground="#000000")
        self.entry_key.configure(highlightbackground="#ffffff")
        self.entry_key.configure(highlightcolor="black")
        self.entry_key.configure(insertbackground="black")
        self.entry_key.configure(selectbackground="blue")
        self.entry_key.configure(selectforeground="white")
        self.entry_key.configure(textvariable=Teacher - Create Class_support.enroll_key)

        self.key_y = tk.Radiobutton(self.enrollment_key)
        self.key_y.place(relx=0.032, rely=0.222, relheight=0.278, relwidth=0.161
                , bordermode='ignore')
        self.key_y.configure(activebackground="white")
        self.key_y.configure(activeforeground="#000000")
        self.key_y.configure(background="#ffffff")
        self.key_y.configure(disabledforeground="#bfbfbf")
        self.key_y.configure(foreground="#000000")
        self.key_y.configure(highlightbackground="#ffffff")
        self.key_y.configure(highlightcolor="black")
        self.key_y.configure(justify='left')
        self.key_y.configure(selectcolor="#05bff5")
        self.key_y.configure(text='''Yes''')
        self.key_y.configure(variable=Teacher - Create Class_support.selectedButton)

        self.key_n = tk.Radiobutton(self.enrollment_key)
        self.key_n.place(relx=0.194, rely=0.222, relheight=0.278, relwidth=0.161
                , bordermode='ignore')
        self.key_n.configure(activebackground="white")
        self.key_n.configure(activeforeground="#000000")
        self.key_n.configure(background="#ffffff")
        self.key_n.configure(disabledforeground="#bfbfbf")
        self.key_n.configure(foreground="#000000")
        self.key_n.configure(highlightbackground="#ffffff")
        self.key_n.configure(highlightcolor="black")
        self.key_n.configure(justify='left')
        self.key_n.configure(selectcolor="#05bff5")
        self.key_n.configure(text='''No''')
        self.key_n.configure(variable=Teacher - Create Class_support.selectedButton)

        self.create_butt = tk.Button(self.create_class)
        self.create_butt.place(relx=0.435, rely=0.808, height=30, width=60
                , bordermode='ignore')
        self.create_butt.configure(activebackground="#05bff5")
        self.create_butt.configure(activeforeground="white")
        self.create_butt.configure(background="white")
        self.create_butt.configure(disabledforeground="#bfbfbf")
        self.create_butt.configure(font="-family {Arcon Rounded-} -size 9 -weight bold")
        self.create_butt.configure(foreground="#05bff5")
        self.create_butt.configure(highlightbackground="#ffffff")
        self.create_butt.configure(highlightcolor="black")
        self.create_butt.configure(pady="0")
        self.create_butt.configure(text='''create''')

if __name__ == '__main__':
    vp_start_gui()





